export const MOCK_STATS = {
  totalCustomers: 1234,
  activeSubscriptions: 856,
  pendingServices: 42,
  totalRevenue: '₹47,00,000',
  customerGrowth: 12,
  subscriptionGrowth: 8,
  serviceGrowth: -3,
  revenueGrowth: 15,
};

export const MOCK_CUSTOMERS = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh@example.com',
    phone: '+91 98765-43210',
    location: 'Mumbai, Maharashtra',
    status: 'active',
    systemSize: '6.5 kW',
    installDate: '2023-06-15',
    totalSpent: '₹8,50,000',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+91 98765-43211',
    location: 'Delhi, Delhi',
    status: 'active',
    systemSize: '8.2 kW',
    installDate: '2023-08-20',
    totalSpent: '₹12,50,000',
  },
  {
    id: '3',
    name: 'Amit Patel',
    email: 'amit@example.com',
    phone: '+91 98765-43212',
    location: 'Bangalore, Karnataka',
    status: 'pending',
    systemSize: '5.0 kW',
    installDate: '2024-01-10',
    totalSpent: '₹6,20,000',
  },
  {
    id: '4',
    name: 'Neha Gupta',
    email: 'neha@example.com',
    phone: '+91 98765-43213',
    location: 'Chennai, Tamil Nadu',
    status: 'active',
    systemSize: '7.5 kW',
    installDate: '2023-11-05',
    totalSpent: '₹10,80,000',
  },
  {
    id: '5',
    name: 'Rahul Singh',
    email: 'rahul@example.com',
    phone: '+91 98765-43214',
    location: 'Hyderabad, Telangana',
    status: 'inactive',
    systemSize: '4.8 kW',
    installDate: '2022-03-22',
    totalSpent: '₹5,50,000',
  },
];

export const MOCK_Partner = [
  {
    id: '1',
    name: 'Vikram Joshi',
    email: 'vikram@solarxpert.com',
    phone: '+91 98765-12345',
    status: 'active',
    region: 'Maharashtra',
    customersAssigned: 45,
    totalSales: 12,
  },
  {
    id: '2',
    name: 'Anita Reddy',
    email: 'anita@solarxpert.com',
    phone: '+91 98765-12346',
    status: 'active',
    region: 'Karnataka',
    customersAssigned: 52,
    totalSales: 15,
  },
  {
    id: '3',
    name: 'Suresh Iyer',
    email: 'suresh@solarxpert.com',
    phone: '+91 98765-12347',
    status: 'inactive',
    region: 'Tamil Nadu',
    customersAssigned: 28,
    totalSales: 0,
  },
];

export const MOCK_ENGINEERS = [
  {
    id: '1',
    name: 'Rohan Mehta',
    email: 'rohan@solarxpert.com',
    phone: '+91 98765-55510',
    status: 'active',
    certification: 'Master Electrician',
    completedProjects: 78,
    activeProjects: 5,
  },
  {
    id: '2',
    name: 'Divya Krishnan',
    email: 'divya@solarxpert.com',
    phone: '+91 98765-55520',
    status: 'active',
    certification: 'Solar Installer',
    completedProjects: 62,
    activeProjects: 3,
  },
  {
    id: '3',
    name: 'Karthik Rao',
    email: 'karthik@solarxpert.com',
    phone: '+91 98765-55530',
    status: 'active',
    certification: 'Master Electrician',
    completedProjects: 91,
    activeProjects: 4,
  },
];

export const MOCK_SERVICES = [
  {
    id: 'SVC001',
    customerName: 'Rajesh Kumar',
    type: 'Installation',
    status: 'in-progress',
    date: '2024-01-15',
    assignedEngineer: 'Rohan Mehta',
    description: 'Solar panel installation for 6.5 kW system',
  },
  {
    id: 'SVC002',
    customerName: 'Priya Sharma',
    type: 'Maintenance',
    status: 'completed',
    date: '2024-01-10',
    assignedEngineer: 'Divya Krishnan',
    description: 'Monthly maintenance check',
  },
  {
    id: 'SVC003',
    customerName: 'Amit Patel',
    type: 'Repair',
    status: 'pending',
    date: '2024-01-20',
    assignedEngineer: 'Karthik Rao',
    description: 'Inverter replacement',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: '1',
    title: 'New Service Request',
    description: 'Neha Gupta requested installation inspection',
    type: 'info',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: '2',
    title: 'Payment Received',
    description: 'Payment of ₹2,45,000 received from Priya Sharma',
    type: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: '3',
    title: 'Installation Complete',
    description: 'Installation at Rajesh Kumar\'s property is complete',
    type: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
  },
];

export const DASHBOARD_MENU = [
  { label: 'Dashboard', value: 'dashboard' },
  { label: 'Customers', value: 'customers' },
  { label: 'Partner', value: 'Partner' },
  { label: 'Engineers', value: 'engineers' },
  { label: 'Subscriptions', value: 'subscriptions' },
  { label: 'Services', value: 'services' },
  { label: 'Installations', value: 'installations' },
  { label: 'Settings', value: 'settings' },
];
