export const MOCK_STATS = {
  totalCustomers: 1234,
  activeSubscriptions: 856,
  pendingServices: 42,
  totalRevenue: '$145,230',
  customerGrowth: 12,
  subscriptionGrowth: 8,
  serviceGrowth: -3,
  revenueGrowth: 15,
};

export const MOCK_CUSTOMERS = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '+1 234-567-8901',
    location: 'Los Angeles, CA',
    status: 'active',
    systemSize: '6.5 kW',
    installDate: '2023-06-15',
    totalSpent: '$12,450',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '+1 234-567-8902',
    location: 'San Francisco, CA',
    status: 'active',
    systemSize: '8.2 kW',
    installDate: '2023-08-20',
    totalSpent: '$18,750',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael@example.com',
    phone: '+1 234-567-8903',
    location: 'San Diego, CA',
    status: 'pending',
    systemSize: '5.0 kW',
    installDate: '2024-01-10',
    totalSpent: '$8,900',
  },
  {
    id: '4',
    name: 'Emma Davis',
    email: 'emma@example.com',
    phone: '+1 234-567-8904',
    location: 'Berkeley, CA',
    status: 'active',
    systemSize: '7.5 kW',
    installDate: '2023-11-05',
    totalSpent: '$15,200',
  },
  {
    id: '5',
    name: 'Robert Wilson',
    email: 'robert@example.com',
    phone: '+1 234-567-8905',
    location: 'Oakland, CA',
    status: 'inactive',
    systemSize: '4.8 kW',
    installDate: '2022-03-22',
    totalSpent: '$9,600',
  },
];

export const MOCK_AGENTS = [
  {
    id: '1',
    name: 'Alex Turner',
    email: 'alex@solarflow.com',
    phone: '+1 555-123-4567',
    status: 'active',
    region: 'Northern CA',
    customersCount: 45,
    thisMonth: 12,
  },
  {
    id: '2',
    name: 'Jessica Brown',
    email: 'jessica@solarflow.com',
    phone: '+1 555-234-5678',
    status: 'active',
    region: 'Southern CA',
    customersCount: 52,
    thisMonth: 15,
  },
  {
    id: '3',
    name: 'David Martinez',
    email: 'david@solarflow.com',
    phone: '+1 555-345-6789',
    status: 'inactive',
    region: 'Central CA',
    customersCount: 28,
    thisMonth: 0,
  },
];

export const MOCK_ENGINEERS = [
  {
    id: '1',
    name: 'Thomas Anderson',
    email: 'thomas@solarflow.com',
    phone: '+1 555-555-1111',
    status: 'active',
    certification: 'Master Electrician',
    completedProjects: 78,
    activeProjects: 5,
  },
  {
    id: '2',
    name: 'Maria Garcia',
    email: 'maria@solarflow.com',
    phone: '+1 555-555-2222',
    status: 'active',
    certification: 'Solar Installer',
    completedProjects: 62,
    activeProjects: 3,
  },
  {
    id: '3',
    name: 'James Lee',
    email: 'james@solarflow.com',
    phone: '+1 555-555-3333',
    status: 'active',
    certification: 'Master Electrician',
    completedProjects: 91,
    activeProjects: 4,
  },
];

export const MOCK_SERVICES = [
  {
    id: 'SVC001',
    customerName: 'John Smith',
    type: 'Installation',
    status: 'in-progress',
    date: '2024-01-15',
    assignedEngineer: 'Thomas Anderson',
    description: 'Solar panel installation for 6.5 kW system',
  },
  {
    id: 'SVC002',
    customerName: 'Sarah Johnson',
    type: 'Maintenance',
    status: 'completed',
    date: '2024-01-10',
    assignedEngineer: 'Maria Garcia',
    description: 'Monthly maintenance check',
  },
  {
    id: 'SVC003',
    customerName: 'Michael Chen',
    type: 'Repair',
    status: 'pending',
    date: '2024-01-20',
    assignedEngineer: 'James Lee',
    description: 'Inverter replacement',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: '1',
    title: 'New Service Request',
    description: 'Emma Davis requested installation inspection',
    type: 'info',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: '2',
    title: 'Payment Received',
    description: 'Payment of $2,450 received from Sarah Johnson',
    type: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: '3',
    title: 'Installation Complete',
    description: 'Installation at John Smith&apos;s property is complete',
    type: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
  },
];

export const DASHBOARD_MENU = [
  { label: 'Dashboard', value: 'dashboard' },
  { label: 'Customers', value: 'customers' },
  { label: 'Agents', value: 'agents' },
  { label: 'Engineers', value: 'engineers' },
  { label: 'Subscriptions', value: 'subscriptions' },
  { label: 'Services', value: 'services' },
  { label: 'Installations', value: 'installations' },
  { label: 'Payments', value: 'payments' },
  { label: 'Reports', value: 'reports' },
  { label: 'Notifications', value: 'notifications' },
  { label: 'Settings', value: 'settings' },
];
